// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BlockUiController from "./block_ui_controller"
application.register("block-ui", BlockUiController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)
